/*
 * Episteme - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 */

package org.episteme.core.mathematics.loaders.matrixmarket;

import org.episteme.core.io.AbstractResourceWriter;
import org.episteme.core.mathematics.linearalgebra.Matrix;
import org.episteme.core.mathematics.numbers.real.Real;

import java.io.*;

/**
 * Writer for the NIST MatrixMarket (.mtx) format.
 * Exports matrices into Coordinate format.
 *
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @since 1.2
 */
public class MatrixMarketWriter extends AbstractResourceWriter<Matrix<?>> {

    public MatrixMarketWriter() {
    }

    @Override
    public String getResourcePath() {
        return "data/matrices";
    }

    @Override
    @SuppressWarnings("unchecked")
    public Class<Matrix<?>> getResourceType() {
        return (Class<Matrix<?>>) (Class<?>) Matrix.class;
    }

    @Override
    public String getName() {
        return "MatrixMarket Writer";
    }

    @Override
    public String getDescription() {
        return "Exports matrices in NIST MatrixMarket (.mtx) Coordinate format.";
    }

    @Override
    public String getLongDescription() {
        return "Serializes dense and sparse matrices into the standard MatrixMarket interchange format.";
    }

    @Override
    public String getCategory() {
        return "Mathematics";
    }

    @Override
    public String[] getSupportedVersions() {
        return new String[] {"2.0"};
    }

    @Override
    public String[] getSupportedExtensions() {
        return new String[] {".mtx", ".mm"};
    }

    @Override
    public void save(Matrix<?> matrix, String destination) throws Exception {
        File file = new File(destination);
        File parent = file.getParentFile();
        if (parent != null && !parent.exists()) {
            parent.mkdirs();
        }
        try (FileWriter fw = new FileWriter(file, java.nio.charset.StandardCharsets.UTF_8)) {
            write(matrix, fw);
        }
    }

    public void write(Matrix<?> matrix, Writer writer) throws IOException {
        PrintWriter pw = new PrintWriter(writer);
        int rows = matrix.rows();
        int cols = matrix.cols();

        // Count non-zeros
        int nnz = 0;
        double tol = 1e-15;
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                Object val = matrix.get(i, j);
                double dVal = toDouble(val);
                if (Math.abs(dVal) > tol) {
                    nnz++;
                }
            }
        }

        // Header
        pw.println("%%MatrixMarket matrix coordinate real general");
        pw.println("% Generated by Episteme Framework");
        pw.println(rows + " " + cols + " " + nnz);

        // Entries (1-based indices)
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                Object val = matrix.get(i, j);
                double dVal = toDouble(val);
                if (Math.abs(dVal) > tol) {
                    pw.printf(java.util.Locale.US, "%d %d %.12g%n", (i + 1), (j + 1), dVal);
                }
            }
        }
        pw.flush();
    }

    private double toDouble(Object val) {
        if (val == null) return 0.0;
        if (val instanceof Number n) return n.doubleValue();
        if (val instanceof Real r) return r.doubleValue();
        return Double.parseDouble(val.toString());
    }
}
